version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: feedbackdb
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3303:3306
    volumes:
      - .m2:/root/.m2   
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8082:8081
    depends_on:
      - mysqldb
    environment:  
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/feedbackdb?allowPublicKeyRetrieval=true  
      - spring.datasource.username=root
      - spring.datasource.password=root
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: